### ISSUE TITLE
E_WARNING: array_map(): An error occurred while invoking the map callback

### ISSUE THREAD

**Issue by chriskl** [tijsverkoyen/CssToInlineStyles#103]
Hi, 

We constantly get the error in the subject on our production server.  We have NewRelic monitoring on which is how we see it.  We recently updated to 1.5.4 version of the library to see if that resolves it, but it doesn't.  Here is the error and stack trace (minus our code's part of the stack):

```
Error message
E_WARNING: array_map(): An error occurred while invoking the map callback

Stack trace
…vendor/symfony/css-selector/Symfony/Component/CssSelector/XPath/
Translator.php (0)
…gate/vendor/symfony/css-selector/Symfony/Component/CssSelector/
CssSelector.php (65)
….4/navigate/vendor/tijsverkoyen/css-to-inline-styles/src/
CssToInlineStyles.php (165)
```

**Comment by barryvdh** [comment]
Can you post your html/css in a gist?

**Comment by chriskl** [comment]
That'll be a challenge...I'll get someone on to it...

**Comment by barryvdh** [comment]
Well, otherwise it would be hard to test.
But preferably you strip as much as the html/css as possible, while still getting the error.

**Comment by stof** [comment]
This issue was finxed in the Symfony CssSelector component in https://github.com/symfony/symfony/commit/38e9623ca4bf1a60009141f1a0f895be621da8ec Just make sure you use an uptodate version of the component (i.e. ``>=2.3.21, < 2.4`` or ``>=2.5.6``)
