### ISSUE TITLE
$cssRules Memory Leak

### ISSUE THREAD

**Issue by jproffitt3ge** [tijsverkoyen/CssToInlineStyles#105]
I'm using this to inline emails in bulk, and I noticed while profiling that each email I inlined took longer to convert than the last. I traced it back to the "cssRules" variable, which gets appended to every time "processCSS" is called, even if the css and html are exactly the same as the last time it was called.

Is there a reason for this variable to live outside the "convert" function scope? Would it make sense to change the code so that processCSS returns a list of rules rather than modifying any state?

``` 
$cssRules = $this->processCSS();
```

**Comment by tijsverkoyen** [comment]
This will be fixed in #111

**Comment by stof** [comment]
Actually, this has been fixed by #106 in 1.x, so it should be closed
