### ISSUE TITLE
Remove the css, html and cssRules as properties (keep wrapper class for BC)

### ISSUE THREAD

**Issue by Hikariii** [tijsverkoyen/CssToInlineStyles#109]
I think this class would benefit greatly from separating the ```$html```, ```$css``` and ```$cssRules``` properties (data) and the data processing methods.

Currently people are having issues because all of the conversion is done in one method, using internal properties for their data.
See https://github.com/tijsverkoyen/CssToInlineStyles/pull/106 and https://github.com/tijsverkoyen/CssToInlineStyles/pull/87

If the css and html data could be injected into a conversion method, we could cache (css-rule) data externally if needed and inject cached data if needed.
Also memory issues will be a thing of the past.

We could keep the current class as wrapper for backwards compatibility to keep containing html and css data like the current class and move the html processing to a separate class. This publicly available class for css processing could then be used in different projects that want to manage their css and html data outside of the conversion class.

Also see https://github.com/tijsverkoyen/CssToInlineStyles/pull/87#issuecomment-147701892

**Comment by tijsverkoyen** [comment]
This will be fixed in #111
