### ISSUE TITLE
composer error

### ISSUE THREAD

**Issue by androdel** [tijsverkoyen/CssToInlineStyles#120]
I get the following message when I want to install your package: 

[InvalidArgumentException]
  Could not find package inlinestyle/inlinestyle at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability

I removed the minimum-stability and tried again, but without result. Any idea?

**Comment by hkdobrev** [comment]
@androdel You should use `tijsverkoyen/css-to-inline-styles`, not `inslinestyle/inlinestyle`.

**Comment by androdel** [comment]
Sorry, used the wrong error message. It's this one: [InvalidArgumentException]
  Could not find package tijsverkoyen/css-to-inline-styles at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability

**Comment by hkdobrev** [comment]
@androdel Try removing the package from your `composer.json` and using the `composer require` command listed in the readme. It will find an appropriate version constraint automatically for you :wink:

**Comment by androdel** [comment]
I did: 

![composer-error](https://cloud.githubusercontent.com/assets/13794129/11690217/e5a94ace-9e95-11e5-9a61-b0a862bf6445.jpg)

**Comment by stof** [comment]
@androdel have you disabled packagist in your composer.json (or in your global ``~/.composer/config.json`` ?

**Comment by androdel** [comment]
The packagist was indeed disabled. Removing it dit the trick. Thanks for the tip!
