### ISSUE TITLE
&nbsp; is converted as Â&nbsp;

### ISSUE THREAD

**Issue by jmp909** [tijsverkoyen/CssToInlineStyles#124]
`&nbsp;` is converted to `Â&nbsp;`

I'm not sure if there's something I need to set in config?

thanks
J

**Comment by jmp909** [comment]
sorry. i needed to set PHPMailer to UTF-8 as well

`$mail->CharSet = "UTF-8";`

**Comment by lexdubyna** [comment]
I am experiencing the same issue, while also using PHPMailer  
Setting `$mail->CharSet = "UTF-8";` didn't help me
