### ISSUE TITLE
Give workaround example for known issue: not supporting pseudo-selectors or fix it

### ISSUE THREAD

**Issue by tpraxl** [tijsverkoyen/CssToInlineStyles#126]
Hello Tijs,

thanks for the good work on CssToInlineStyles.
You mention the known issue "no support for pseudo selectors" in README.md

From my point of view, this is no big deal, even if styles are stripped out, because CssToInlineStyles will keep media queries in the style block. So you could give an example for the workaround in README.md just where the known issue gets mentioned:

```
If you need pseudo selectors, wrap them in @media all{ }
```

On the other hand: 
Why not support it? If there's no conceptional reason for not supporting it, I'd offer you to help.
Let me know if you're interested.

**Comment by barryvdh** [comment]
It's just not possible to inline psuedo selectors like `:hover`.

**Comment by tpraxl** [comment]
Well, I didn't talk about inline-pseudo-selectors, but about the fact that they will not be inlined **and ** get stripped out. They should be kept in the inline style-block, IMHO, not being removed.

**Comment by barryvdh** [comment]
You can use `stripOriginalStyleTags(false)`, or is that not what you mean? 
In v2 they should always be kept; https://github.com/tijsverkoyen/CssToInlineStyles/pull/111

**Comment by tpraxl** [comment]
I want to strip all styles of the styleblock that can be inlined, but keep those not able to be inlined.

Personally, I would wrap pseudo-selectors in @media all{} in order to prevent stripping them out. 

Just thought it would help others to either document that solution or support pseudo selectors (by keeping them in the style block). 
After all, the visual representation should not change after inlining the styles.

**Comment by tpraxl** [comment]
> In v2 they should always be kept; #111
Oh, great. So in v2 you can choose to `stripOriginalStyleTags(true)` but pseudo selectors will not be removed? Right? This would be exactly what I wanted.

**Comment by barryvdh** [comment]
No in v1 you can choose, in v2 they will be always kept.

**Comment by tpraxl** [comment]
uh.. Sorry, I didn't follow the discussion on v2. 

> in v2 they will be always kept.

That would make it uncomfortable for the use case of creating html-newsletters, which is exactly what I plan to use CssToInlineStyles for. 
When you're dealing with large newsletters, you need to keep an eye on the size, otherwise you get issues with certain e-mail-clients especially on mobile-devices. Stripping out unneeded css is one of the things you usually want to do.
