### ISSUE TITLE
Version 2.0 media queries just stripped?

### ISSUE THREAD

**Issue by luwes** [tijsverkoyen/CssToInlineStyles#135]
Am I missing something or are media queries stripped out of the stylesheets and not injected back in to the head for example?

**Comment by tijsverkoyen** [comment]
media-queries can't be inlined.

**Comment by luwes** [comment]
Thanks for the quick response. That's true but they shouldn't be discarded completely I think. It's still valuable to put just the media queries back in the head in a style element.

Anyway thanks for a great library! Cheers

**Comment by drasill** [comment]
Hi,

it seems it's used by Foundation For Emails : 


> Our web inliner automates this process for you. To use it, paste in the contents of index.html into the HTML field, paste in the contents of css/foundation-emails.css into the CSS field, and then press "Inline!". Once it's done, you'll see a large soup of HTML that is your inlined email.
> 
> **Your email's CSS will include media queries for responsive styling which the inliner tool will move into the <body> so they are preserved.**

(https://foundation.zurb.com/emails/docs/css-guide.html, section "Inlining")

So, I can't use CssToInlineStyles with it :/

**Comment by Kocal** [comment]
Is there a way to find medias queries and export them into a single `<style>`?
