### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by malakana** [tijsverkoyen/CssToInlineStyles#136]
In the example given, $html and $css are parameters in the convert method not in the construct method

**Comment by TomCorvus** [comment]
It should look like this:

`use TijsVerkoyen\CssToInlineStyles\CssToInlineStyles;

$html = file_get_contents(__DIR__ . '/examples/sumo/index.htm');
$css = file_get_contents(__DIR__ . '/examples/sumo/style.css');

// create instance
$cssToInlineStyles = new CssToInlineStyles($html, $css);

// output
echo $cssToInlineStyles->convert();`

**Comment by stof** [comment]
the issue is that you are reading the readme in the master branch, not in the version of the library you are using. In the master branch, they are arguments of the ``convert`` method
