### ISSUE TITLE
Replace DOMDocument::saveXML with DOMDocument::saveHTML

### ISSUE THREAD

**Issue by josh18** [tijsverkoyen/CssToInlineStyles#141]
Is there a reason that saveXML (line 118, `src/CssToInlineStyles.php`) is used instead of saveHTML or is it just a typo? Just asking as this fixes a couple of small bugs that I found such as adding `<![CDATA[ ]]>` inside `<style>` tags.

**Comment by voku** [comment]
In the old version (~1.0) "saveHTML()" was used by default, don't know why it was removed but probably because no test is available for this use case!?

-> https://github.com/tijsverkoyen/CssToInlineStyles/blob/1.5.5/src/CssToInlineStyles.php#L378

**Comment by stof** [comment]
should be closed as #154 has been merged
