### ISSUE TITLE
CSS applied to head elements?

### ISSUE THREAD

**Issue by zmip** [tijsverkoyen/CssToInlineStyles#142]
Maybe I'm not following your logic, but if I take the "Basic" email template from Zurb:

http://zurb.com/playground/responsive-email-templates

Feed the HTML and CSS file contents to `CssToInlineStyles->convert()`, I end up with css applied to **all** the head tags. Is this by design?

``` html
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml" style="margin: 0; padding: 0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;">
  <head style="margin: 0; padding: 0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;">
<!-- If you delete this meta tag, Half Life 3 will never be released. -->
    <meta name="viewport" content="width=device-width" style="margin: 0; padding: 0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" style="margin: 0; padding: 0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;" />
    <title style="margin: 0; padding: 0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;">ZURBemails</title>
    <link rel="stylesheet" type="text/css" href="stylesheets/email.css" style="margin: 0; padding: 0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;" />
  </head>
```

**Comment by josh18** [comment]
I'm guessing you are using the `*` so technically it is correct but it is probably unintentional. For a quick fix you could change it to `body, body *` or `*:not(head):not(meta):not(title):not(link)` (haven't tested but I think it should work).

**Comment by zmip** [comment]
Yeah Josh, thanks. I also figured it's the * in the CSS that makes it apply it to everything. But to applying * to tags in `<head>` would be something you'd want to avoid. The CSS wildcard isn't used often, but it's valid CSS. It shouldn't mess up your HTML. I'd consider this a bug unless there's a case where CSS in head tags is required (I can't think of any).
