### ISSUE TITLE
<br> is converted to <br></br>

### ISSUE THREAD

**Issue by gharlan** [tijsverkoyen/CssToInlineStyles#144]
`<br>` and `<br />` are converted to `<br></br>`

**Comment by gharlan** [comment]
It seems to work when using `saveHTML` instead of `saveXML`:
https://github.com/tijsverkoyen/CssToInlineStyles/blob/master/src/CssToInlineStyles.php#L124

**Comment by spike31** [comment]
You can try to override the `getHtmlFromDocument` method and disable the parameters `LIBXML_NOEMPTYTAG` because `Expand empty tags (e.g. <br/> to <br></br>)`. And it's not very cool..

Take a look at http://php.net/manual/en/libxml.constants.php,

**Comment by gharlan** [comment]
I guess an empty `<p></p>` tag would become `<p/>` then.
I still think, that `saveHtml` would be the correct way.
http://php.net/manual/en/domdocument.savehtml.php

**Comment by OsoianMarcel** [comment]
Up!

**Comment by eldan88** [comment]
I am having the same problem. I used div tags as line breaks

**Comment by josh18** [comment]
Note that this is fixed in #154

**Comment by eldan88** [comment]
is it updated on packagist? Why is this issue still open then?

**Comment by josh18** [comment]
Because the pull request hasn't been accepted yet.

**Comment by stof** [comment]
@tijsverkoyen this issue should be closed as the PR has been merged
