### ISSUE TITLE
The 2.0 branch should be removed

### ISSUE THREAD

**Issue by stof** [tijsverkoyen/CssToInlineStyles#151]
This branch does not contain the final version of the 2.0 release (it is older than that) so it is not a maintenance branch for the release. I was probably the feature branch for the PR doing the initial work.
Thus, as it is named 2.0, composer will detect it as a versionned branch, so someone asking for ``2.0.*@dev`` might get this branch.

so it should be removed to avoid confusing users and composer.

**Comment by tijsverkoyen** [comment]
Fixed
