### ISSUE TITLE
xmlns is duplicated

### ISSUE THREAD

**Issue by Stadly** [tijsverkoyen/CssToInlineStyles#157]
When running an xhtml file with `<html xmlns="http://www.w3.org/1999/xhtml">` through `CssToInlineStyles`, the `xmlns` attribute is duplicated. Example:

Input:

    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml">
       <head>
          <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
          <title>Title</title>
       </head>
       <body>
          <div>Message</div>
       </body>
    </html>

Output:

    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Title</title>
      </head>
      <body>
              <div>Message</div>
           </body>
    </html>

**Comment by stof** [comment]
does it still happen in the latest version ?

**Comment by Stadly** [comment]
No. With the latest version I get this result:

    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Title</title>
    </head>
    <body>
          <div>Message</div>
       </body>
    </html>

So the issue with double xmlns is fixed. Another issue is introduced, however: Void elements are no longer self-closing. The `/` at the end of the `<meta>` element is removed, even though the doctype is `xhtml`. This also happens with `img`, `br`, and `hr`, so it probably applies to all void elements. I'll open a separate issue on this.

**Comment by Stadly** [comment]
No. With the latest version I get this result:

    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Title</title>
    </head>
    <body>
          <div>Message</div>
       </body>
    </html>

So the issue with double xmlns is fixed. Another issue is introduced, however: Void elements are no longer self-closing. The `/` at the end of the `<meta>` element is removed, even though the doctype is `xhtml`. This also happens with `img`, `br`, and `hr`, so it probably applies to all void elements. I'll open a separate issue on this.
