### ISSUE TITLE
Remove inline style tags

### ISSUE THREAD

**Issue by sylfabre** [tijsverkoyen/CssToInlineStyles#165]
Is there a way to remove inline style tags after the conversion as they are not needed anymore?

I would like to turn
```
<html>
	<head>
		<style>
			div {color: red;}
		</style>
	</head>
	<body>
		<div>Hello world!</div>
	</body>
</html>
```
into
```
<html>
	<head>
	</head>
	<body>
		<div style="color: red">Hello world!</div>
	</body>
</html>
```
with 
```
$css = new TijsVerkoyen\CssToInlineStyles\CssToInlineStyles();
$css->convert($html);
```

**Comment by sylfabre** [comment]
Right now I get
```
<html>
<head><style>
			div {color: red;}
		</style></head>
<body>
		<div style="color: red;">Hello world!</div>
	</body>
</html>
```

**Comment by stof** [comment]
they may still be needed if they contain media queries or styles for states (hover, active, etc...) as these cannot be inlined

**Comment by sylfabre** [comment]
@stof right! But is it possible to remove style content not needed?
I'm hitting a Spam Assassin rule about too much HTML vs text in the body so I'm looking a way to remove all unnecessary HTML ...

**Comment by tijsverkoyen** [comment]
@sylfabre you can remove them yourself with a regex.
