### ISSUE TITLE
No Html provided error

### ISSUE THREAD

**Issue by eldan88** [tijsverkoyen/CssToInlineStyles#167]
I am not sure what happened. But all of a sudden I keep getting this issue. I have echoed out the HTML variable and it does show the HTML code. I don't know I keep on getting this issue. 

Any help would be really appreciated. Thanks

```
use TijsVerkoyen\CssToInlineStyles\CssToInlineStyles; //Make sure the composer autoload is always set to true in order for this to work


class test{

    public function test1(){

        $test =  new CssToInlineStyles();
$html = file_get_contents('test2.html');
$css = file_get_contents('test1.css');
        
       try {


            echo $test->convert($html, $css);

        }catch (Exception $e){
            FB::send($e);
        }

    }

}

$test = new test();
$test->test1();

```

**Comment by stof** [comment]
Which version of the library are you using ?

**Comment by eldan88** [comment]
The latest one v 2.2

**Comment by eldan88** [comment]
Nevermind. I updated all my composer dependencies and it worked. Thank you!

**Comment by christophermiles** [comment]
I am also getting this error, using `1.5.5`. Likewise, the `$html` variable is definitely returning valid HTML with UTF-8 charset defined as recommended in the 'Known issues' in the docs.

What is the minimum version I need to solve this issue? I cannot use the latest release because I have a nightmare of conflicting dependencies based on the version of Symfony we are running.

**Comment by christophermiles** [comment]
I discovered that this was due to version 1.5.5 requiring HTML to be passed using the `->setHtml()` method, rather than just passing HTML to the convert function as described in the current documentation

**Comment by stof** [comment]
@christophermiles if you use the 1.x version, read the documentation in the 1.x source code, not the documentation of 2.x
