### ISSUE TITLE
syntax issue with php version 5.3

### ISSUE THREAD

**Issue by howdu** [tijsverkoyen/CssToInlineStyles#169]
composer.json says 5.3.0 but I'm testing this on 5.3.29 and it's throwing a syntax error.

Parse error: syntax error, unexpected T_CLASS, expecting T_STRING or T_VARIABLE or '$' in /CssToInlineStyles/src/CssToInlineStyles.php on line 160

Points to this line:
`usort($rules, array(RuleProcessor::class, 'sortOnSpecificity'));`

**Comment by stof** [comment]
Latest version requires PHP 5.5

which version are you using ?

**Comment by howdu** [comment]
Sorry, my mistake the composer.json is correct must have been looking at older release. I got it working by downgrading to version: 1.5.5. 

Also I had to add this in for compatility with new/old versions of this library. 
```php
if (method_exists($cssToInlineStyles, 'setHtml')) {
    $cssToInlineStyles->setCSS($this->css);
    $cssToInlineStyles->setHtml($html);
    $this->html = $cssToInlineStyles->convert();
} else {
    $this->html = $cssToInlineStyles->convert($html, $this->css);
}
```

**Comment by stof** [comment]
well, version 1 and version 2 indeed have different APIs (which is why it was a version 2)
