### ISSUE TITLE
Tag 2.2.1 release please?

### ISSUE THREAD

**Issue by GrahamCampbell** [tijsverkoyen/CssToInlineStyles#176]
:)

**Comment by cordoval** [comment]
bump @stof 👍

**Comment by GrahamCampbell** [comment]
Ping.

**Comment by cordoval** [comment]
@GrahamCampbell don't dispair, @stof does not need to be reminded he is a machine 👍

**Comment by taylorotwell** [comment]
Can this be done?

**Comment by cordoval** [comment]
if @taylorotwell is request it this time is a sure thing. 👴 🗝

**Comment by barryvdh** [comment]
Thank you! https://github.com/tijsverkoyen/CssToInlineStyles/releases/tag/2.2.1

**Comment by GrahamCampbell** [comment]
![parrot](https://eikmo72643.i.lithium.com/t5/image/serverpage/image-id/55376i0711447642169488?v=1.0)
