### ISSUE TITLE
Tailwind css cannot be fully processed

### ISSUE THREAD

**Issue by seyfer** [tijsverkoyen/CssToInlineStyles#209]
Hello!

I have a setup with Laravel Mix and some basic css file. When I import `tailwind` and try to inline css - it works only if I do not include `tailwind` utilities.

```
@tailwind base;
@tailwind components;
//doesn't work
//@tailwind utilities;

*,
*:after,
*:before {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
```

is there any way to debug or to make it work?

**Comment by stof** [comment]
What do you mean by "cannot be fully processed" ? Do you get any error ?

**Comment by seyfer** [comment]
@stof when 
`@tailwind utilities;`
uncommented, I do not get any styles inlined. All styles are inside `<style>` tag at the top. But HTML is clean.
When I comment out `@tailwind utilities;` - styles are inlined.

No errors.

**Comment by stof** [comment]
Closing this. `@tailwind utilities;` is not valid CSS but a custom non-standard directive used by the tailwind tooling. You need to use the result of building your CSS for the inlining, not the input.
