### ISSUE TITLE
Add support for symfony/css-selector:6.0

### ISSUE THREAD

**Issue by victorstanciu** [tijsverkoyen/CssToInlineStyles#216]
First of all, thank you for this great library ♥

Symfony 6.0 has been released recently, but any projects that depend on `tijsverkoyen/css-to-inline-styles` can't be upgraded because the dependency on `symfony/css-selector` is limited to `^2.7 || ^3.0 || ^4.0 || ^5.0`.

**Comment by julienmiclo** [comment]
Hello,
same problem here.

Dependency in composer.json are up-to-date but on [packagist](https://packagist.org/packages/tijsverkoyen/css-to-inline-styles) requirements are not ?

Thank you

**Comment by stof** [comment]
By default, packagist shows the latest release, not the dev version. Support for Symfony 6 has been merged but not released yet.

**Comment by stof** [comment]
if you [switch to the dev-master version on Packagist](https://packagist.org/packages/tijsverkoyen/css-to-inline-styles#dev-master), it shows sypport for Symfony 6 in the constraints.

**Comment by julienmiclo** [comment]
Thank you @stof !!

**Comment by stof** [comment]
I'm working on the release

**Comment by stof** [comment]
The release is now done.
