### ISSUE TITLE
IDEA: config file

### ISSUE THREAD

**Issue by nam-co** [tijsverkoyen/CssToInlineStyles#223]
Hi, I think it would be nice to have a way to specify the css file for the complete site, instead of setting it up in every call to the package, if $css == null then get the path of the css file from the config(), what do you think @tijsverkoyen , thanks

**Comment by stof** [comment]
You would still have to configure where this config file is, as this package has no knowledge of the project structure.

So to me, this is better handled at a higher level. You can write a wrapper around the CssToInlineStyles package that configures it according to your needs (or the needs of the framework you use) and then use that wrapper.
