### ISSUE TITLE
Illuminate/Mail Issue

### ISSUE THREAD

**Issue by garethdaine** [tijsverkoyen/CssToInlineStyles#231]
I've come across an issue when using this package as part of Laravel 8 (Illuminate/Mail) when symfony/css-selector is using version 6.0 whereby whenever a mail is sent it results in a **syntax error, unexpected token ")"**.

Versions up to 5.4.3 of symfony/css-selector work fine. I've had to lock the version in composer.json in my project to that version.

This is when running PHP 8, not 8.1.

Not entirely sure if this is something related to this package specifically, or perhaps something in Illuminate/Mail.

**Comment by oliverklee** [comment]
To me, this looks probably rather like an issue in symfony/css-selector, and probably should be reported in the https://github.com/symfony/symfony monorepo instead.

**Comment by garethdaine** [comment]
> To me, this looks probably rather like an issue in symfony/css-selector, and probably should be reported in the https://github.com/symfony/symfony monorepo instead.

Thanks, I have reported it there and also on the Laravel framework.

**Comment by garethdaine** [comment]
@oliverklee I've noticed that in the composer.json of this repo there is a dependency requirement for **"symfony/css-selector": "^2.7 || ^3.0 || ^4.0 || ^5.0 || ^6.0"**, and as **illuminate/mail** has **"tijsverkoyen/css-to-inline-styles": "^2.2.2"** as a requirement, if a **composer update** was ran, would this essentially upgrade **symfony/css-selector** to version 6.0?

With Laravel 8 not being compatible with version 6 of Symfony, this may well be what caused the issue.

**Comment by stof** [comment]
See my answer in https://github.com/symfony/symfony/issues/47064

You need to make sure to tell composer which version of PHP it should target when resolving dependencies, so that you don't get symfony 6.1.0 when running PHP 8.0.
But the requirements here are totally valid and working fine when using composer in the expected way.

**Comment by garethdaine** [comment]
Thanks @stof That solved the issue. Much appreciated.
