### ISSUE TITLE
Undefined property: DOMDocument::$documentElement

### ISSUE THREAD

**Issue by m-shariatzadeh** [tijsverkoyen/CssToInlineStyles#232]
Hi,
i have a problem with this package on shared-hosting while i haven't this problem on localhost

**gives me the error:**

{
    "message": "Undefined property: DOMDocument::$documentElement",
    "exception": "ErrorException",
    "file": "/home/h189025/public_html/system/vendor/tijsverkoyen/css-to-inline-styles/src/CssToInlineStyles.php",
    "line": 132,
    "trace": [
        {
            "file": "/home/h189025/public_html/system/vendor/tijsverkoyen/css-to-inline-styles/src/CssToInlineStyles.php",
            "line": 132,
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "file": "/home/h189025/public_html/system/vendor/tijsverkoyen/css-to-inline-styles/src/CssToInlineStyles.php",
            "line": 50,
            "function": "getHtmlFromDocument",
            "class": "TijsVerkoyen\\CssToInlineStyles\\CssToInlineStyles",
            "type": "->"
        },
        {
            "file": "/home/h189025/public_html/system/vendor/laravel/framework/src/Illuminate/Mail/Markdown.php",
            "line": 74,
            "function": "convert",
            "class": "TijsVerkoyen\\CssToInlineStyles\\CssToInlineStyles",
            "type": "->"
        },
       ....
    ]
}

![Screenshot (391)](https://user-images.githubusercontent.com/56396576/183044068-c963e436-35e3-4df1-82d9-04b21c1ef8dd.png)

please help...

**Comment by SerikK** [comment]
@m-shariatzadeh what was the solution?
