### ISSUE TITLE
PHP 8.2 compatibility

### ISSUE THREAD

**Issue by Ugoku** [tijsverkoyen/CssToInlineStyles#233]
This line has been deprecated in PHP 8.2: `$document->loadHTML(mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8'));`
(`/src/CssToInlineStyles.php` on line 116)

Symfony fixed it like this, but YMMV:

`mb_encode_numericentity($html, [0x80, 0xFFFF, 0, 0xFFFF], 'UTF-8');`

I'll try this and will submit a PR if it works :)

**Comment by stof** [comment]
Can you point me where this is deprecated ? I don't find any RFC about that nor any mention in the PHP 8.2 upgrade file in the PHP repo.

**Comment by driesvints** [comment]
@stof here's an example failure on PHP 8.2: https://github.com/laravel/framework/runs/8245679507?check_suite_focus=true#step:8:91

Here's the upgrade notice: https://github.com/php/php-src/blob/PHP-8.2/UPGRADING#L179-L187

If you look for "mbstring" you can see several PR's made to the core: https://github.com/php/php-src/pulls?q=is%3Apr+Mbstring+is%3Aclosed
