### ISSUE TITLE
`mb_encode_numericentity` vs `htmlspecialchars_decode(htmlentities($html))`

### ISSUE THREAD

**Issue by hirasso** [tijsverkoyen/CssToInlineStyles#246]
Hi there! This is actually not an issue with your library (which is amazing!), rather a question. Feel free to close this if you don't have the time right now :)

I'm in the process of migrating a few projects to PHP 8.2 and trying to find the correct replacement for this:

```php
$document->loadHTML(mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8'))
```

While searching my code base, I found an old version of CssToInlineStyles that was also using this function. And I see that you have replaced it with this since then:

```php
$document->loadHTML(mb_encode_numericentity($html, [0x80, 0x10FFFF, 0, 0x1FFFFF], 'UTF-8'));
```
https://github.com/tijsverkoyen/CssToInlineStyles/blob/83ee6f38df0a63106a9e4536e3060458b74ccedb/src/CssToInlineStyles.php#L116C29-L116C52

This looks very cryptic to me and I'd like to understand better what's going on here. In my (manual) tests, the following worked with all strings that I tested it with:

```php
htmlspecialchars_decode(htmlentities($html));
```

But I'm a bit afraid that I'm missing something...

I'd be grateful for any insight you might have on the matter 🙂

**Comment by Ugoku** [comment]
Hi, not sure if this is still relevant to you but I was the one who submitted patches for this: #234 & #238

The original change came from Symfony, the second patch was suggested by the person who deprecated `HTML-ENTITIES` in PHP itself. The PR's should give a bit more context as to why it was changed like this.
