### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by Ugoku** [tijsverkoyen/CssToInlineStyles#248]
Hi,

5 months ago [a commit](698d3de2eea82519c2acc9855718c4e87aaa2a9a) was made to make this library compatible with PHP 8.4, but no releases have been made since. Can you please make a new release?

**Comment by mralston** [comment]
Is there any chance we can get this released? PHP 8.4 has been released and Laravel uses this package, so there will be a lot of users who will see deprecated messages as they upgrade.

**Comment by Ugoku** [comment]
Pinging @stof and @tijsverkoyen

**Comment by stof** [comment]
I just released version 2.3.0
