### ISSUE TITLE
Parameters out of order

### ISSUE THREAD

**Issue by jp7carlos** [tijsverkoyen/CssToInlineStyles#83]
If i have a CSS like this:
div {
width: 200px;
_width: 211px;
}

The rules will be inserted out of order:
    div style="_width:211px;width:200px;"

If you comment out the lines below the order is respected:
 // sort the pairs
 ksort($pairs);

Is there any reason to sort the pairs?

Thx,
Carlos

**Comment by tijsverkoyen** [comment]
This will be fixed when #111 is merged.
