### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by kalenjordan** [tijsverkoyen/CssToInlineStyles#88]
I started getting segmentation faults this morning in my app after having added some UTF-8 support yesterday.  The change I made was that I began passing in a full html document starting with the doctype and <html>, as opposed to just dropping in my main <div>.

This issue didn't happen in my local environment, only in prod and only some of the time.

After an hour of troubleshooting, turns out that including `<!DOCTYPE html>` in the HTML causes this.

When I removed it, the issue went away:

        $html = "
    -   <!DOCTYPE html>
        <html>
            <head>
                <meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
                <style type='text/css'>" . $this->_getCssInStyleTags() . "</style>
            </head>
            <body>
                $body
            </body>
        </html>
        ";

**Comment by tijsverkoyen** [comment]
I can't reproduce this.
