### ISSUE TITLE
Inlining CSS contained in HTML

### ISSUE THREAD

**Issue by stevenmusumeche** [tijsverkoyen/CssToInlineStyles#93]
Does this class inline the CSS in the HTML's head tag and apply them to the HTML elements?

**Comment by barryvdh** [comment]
Yes

**Comment by stevenmusumeche** [comment]
I'm running some HTML with CSS in the head tag through it and getting back unchanged HTML.

**Comment by stevenmusumeche** [comment]
My mistake, I was not setting setUseInlineStylesBlock
