### ISSUE TITLE
outputXHTML not stripping xml-header correctly

### ISSUE THREAD

**Issue by rvock** [tijsverkoyen/CssToInlineStyles#96]
If the option "outputXHTML" is used, the convert-method tries to remove the xml-header:
https://github.com/tijsverkoyen/CssToInlineStyles/blob/1.5.4/src/CssToInlineStyles.php#L380

This regular expression is not correct. It does not escape the question marks and leaves <? in the resulting html.

This is the correct code:
$html = ltrim(preg_replace('/<\?xml (.*)\?>/', '', $html));

**Comment by barryvdh** [comment]
Can you provide an example of the code you are using exactly?
Would be even better if you can submit a failing testcase and then apply your patch.

**Comment by rvock** [comment]
```
$cssToInlineStyles = new \TijsVerkoyen\CssToInlineStyles\CssToInlineStyles();
$cssToInlineStyles->setHTML('<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />');
$html = $cssToInlineStyles->convert(true);
```

$html equals:
```
<?
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
  </head>
</html>
```

**Comment by jonkoops** [comment]
I am having the same issue, can we get this pull request merged?

**Comment by jonkoops** [comment]
@rvock @barryvdh @tijsverkoyen I've cherry-picked the commits mentioned in this thread and put them in a new pull request.
