### ISSUE TITLE
Inserting A with circumflex character before spans

### ISSUE THREAD

**Issue by Shaktal** [tijsverkoyen/CssToInlineStyles#99]
There is an issue whereby the following code:

     <p>This is a test heading with various things such as <strong>bold</strong>, <span style="text-decoration: underline;"><strong>bold-underline</strong></span><strong></strong>, <em>italics</em>, and various other cool things.</p>

Gets converted to the following:

    <p>This is a test heading with various things such asÂ <strong>bold</strong>,Â <span style="text-decoration: underline;"><strong>bold-underline</strong></span><strong></strong>,Â <em>italics</em>, and various other cool things.</p>

Note the addition of the odd A with circumflex characters. I'm not sure why this occurs.

**Comment by meveridge** [comment]
In my experience this is caused by an invisible character. You can use PHP's ord to find the ASCII code (mine was 194) and then str_replace to get rid of it before passing the HTML in.
```
$html = str_replace(chr(194), chr(32),$html);
```

**Comment by Shaktal** [comment]
I had forgotten that I raised this issue, it turned out not to be an issue with CssToInlineStyles at all, and was in fact a mismatch between the encodings I was using when saving and viewing the message.
